/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package de.microtema.mail;

@org.apache.avro.specific.AvroGenerated
public interface Mail {
    public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Mail\",\"namespace\":\"de.microtema.mail\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"to\",\"type\":\"string\"},{\"name\":\"from\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"string\"}}}");

    /**
     */
    java.lang.CharSequence send(de.microtema.mail.Message message);

    @SuppressWarnings("all")
    public interface Callback extends Mail {
        public static final org.apache.avro.Protocol PROTOCOL = de.microtema.mail.Mail.PROTOCOL;

        /**
         * @throws java.io.IOException The async call could not be completed.
         */
        void send(de.microtema.mail.Message message, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    }
}
